### ISSUE TITLE
Dbii Networks interface

### ISSUE THREAD

**Issue by AsafMag** [danikf/tik4net#26]
When I try to configure the red interface of Dbii Networks, an "unknown parameter" exception is thrown.
As much as I researched, this is because of the `default-name` parameter.

How can I remove it?

**Comment by danikf** [comment]
Hi,

Could you please provide some code?

Thanks,
D

Dne ne 1. dub 2018 8:24 uživatel AsafMag <notifications@github.com> napsal:

**Comment by danikf** [comment]
Hi,
I am not sure which version of library dou sou use, but I am 100% sure that your example works like a charm. 

Instead of sniffer I would recommend you to hook OnWriteRow event on connection to see what is going to the mikrotik router. See [https://github.com/danikf/tik4net/wiki/Communication-debugging-&-testing](this wiki page)

And finaly - if you want to achieve "standard" library behavior with full control of communication, you can use pure connection commands - see https://github.com/danikf/tik4net/wiki/Low-level-API

BTW - 8728 is standard port for mikrotik API and 'trap interupted' is standard behavior when you send bad request :-) 

As last point - there could be problem with encoding - see [https://github.com/danikf/tik4net/wiki/How-to-use-tik4net-library#how-to-encode-non-ascii-characters](notes about encoding)

D

**Comment by AsafMag** [comment]
I think this problem is specific to Dbii's interfaces http://www.dbii.com/f36N-PRO.html
I'll try to find some answers and update

**Comment by danikf** [comment]
Hi,
you can try to use lowlevel API or use "usedFieldsFilter" (last optional parameter in Save method) to specify fields you have modified (to avoid "full save").
D

**Comment by AsafMag** [comment]
I'm using it now, but it's pretty ugly - it makes the user have to know the underlying strings, which is a bad idea for a wrapping library in my opinion.

**Comment by danikf** [comment]
Hi,

in this case - I am not sure - default-name seams to be R/O in mikrotik. So
you could try to patch tik4net sources by setting the property to R/O
(parameter in attribute) - this will instruct engine to skip it during
save. But the filed default-name is not present in InterfaceWireless, so I
expect you tried to use "Intrerface"  and not "InterfaceWireless" ...

Other libraries usually publish just Send/Read API because of variability
of mikrotik commands and types. So wrapping-up the strings could be
sometimes tricky ...

D

2018-04-01 12:59 GMT+02:00 AsafMag <notifications@github.com>:

**Comment by AsafMag** [comment]
I think I figured the `interrupted` bug - both interfaces stop sniffing because of the done / interrupted response to the first one to finish (cancel).

Do you have an idea how to solve this?

**Comment by danikf** [comment]
Hi,

if the appropriate .tag is send with "cancel" command, than it is mikrotik
feature :-) If not, than it is possibly bug in tik4net. I am not sure if it
is possible to sniff more than one interface in one time in mikrotik
because of linux background logic behind the sniffer ...

D

2018-04-01 15:25 GMT+02:00 AsafMag <notifications@github.com>:

**Comment by AsafMag** [comment]
It is possible

**Comment by danikf** [comment]
Hi,
not sure about sniffer (do you reallu use `/tool/sniffer`?), but `/tool/torch` seams to have "singleton" behavior by design.

* Started cmd1, cmd2 (`LoadAsync<ToolTorch>`)
* `cmd2.Cancel`
* Result: both cmd1 and cmd2 cancelled by mikrotik (`.tag` seams to be ignored)

And in console script it looks like:
```
/tool/torch
=interface=ether1
.tag=1

/tool/torch
=interface=wlan1
.tag=2

!re
.....
.....

/cancel
=.tag=2
!trap
=category=2
=message=interrupted
.tag=1

!trap
=category=2
=message=interrupted
.tag=2

!done
.tag=1

!done
.tag=2
```

So - one `cancel` and two canceled commands ... And no exception/error callback from API. This is correct behavoir of API and understandable behavoir of mikrotik router.

D

**Comment by RaelKbg** [comment]
Hi 

when I'm trying to reset-counters im getting wrong command error. Please help

**Comment by danikf** [comment]
Hi RaelKbg - please use your thread with proper name :-)

D

**Comment by RaelKbg** [comment]
Hi danikf

please specify. I used the same code to print where download-used > and it worked fine.

**Comment by danikf** [comment]
Don't use Issue with name "Dbii Networks interface" dor discussion about different topic please ...
+ see my comment in issue #27
D

**Comment by AsafMag** [comment]
Hi,

Actually I use `interface/wireless/sniffer/sniff`

**Comment by RaelKbg** [comment]
Hi AsafMag

Im sorted thank you.

**Comment by AsafMag** [comment]
About the sniffing cancellation - opened issue #35 , closing this one.
