### ISSUE TITLE
ExecuteSingleRowOrDefault Throws Exceptions

### ISSUE THREAD

**Issue by Deantwo** [danikf/tik4net#75]
Same issue as #74

https://github.com/danikf/tik4net/blob/583c41e1a5fa829ea90434a186df140fb66ecd1f/tik4net/Api/ApiCommand.cs#L369

**Comment by danikf** [comment]
Hi, I am not sure what is the problem.

Expected behavior:
0 rows - returns null
1 rows - returns the row
more than 1 rows - throws exception
Mentioned in tests: https://github.com/danikf/tik4net/blob/master/tik4net.tests/TikCommandTest.cs#L239-L262

... which is the same behavior as with standard linq ...OrDefault methods (Linq throws InvalidOperationException in this case).
( ```new List<string>() {"test", "test2" }.SingleOrDefault()``` )

D

**Comment by Deantwo** [comment]
Oh yeah, i found that out when looking at #76.
Forgot to close this one again.
